### ISSUE TITLE
please add   open source alternatives  of Adobe reader   

### ISSUE THREAD

**Issue by josephjosedev** [hasthamalp/LOCKALP#27]
Adobe reader open source  alternatives  are :Okular,Evince

**Comment by dineshkumar12004** [comment]
where should i add ? under which folder ?

**Comment by hasthamalp** [comment]
> where should i add ? under which folder ?

please list below @dineshkumar12004

**Comment by dineshkumar12004** [comment]
> > where should i add ? under which folder ?
> 
> please list below @dineshkumar12004

1. Libreoffice 
2. SumatraPDF
3. Okular
4. Zathura

**Comment by hasthamalp** [comment]
> > > where should i add ? under which folder ?
> > 
> > 
> > please list below @dineshkumar12004
> 
> 1. Libreoffice
> 2. SumatraPDF
> 3. Okular
> 4. Zathura

Thanks for your contribution.we added this shortly ,keep contributing ........  @dineshkumar12004

**Comment by hasthamalp** [comment]
#29  added successfully.
